# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    basic_flow.retainer.cookie:
        class: 'BasicFlowBundle\Retainer\CookieRetainer'
        calls:
            - [setRequest, ["@request_stack"]]

    basic_flow.retainer.session:
        class: 'BasicFlowBundle\Retainer\SessionRetainer'
        calls:
            - [setSession, ["@session"]]
            - [setBasicFlowParams, ["%basic_flow.params%"]]

    basic_flow.step.action_listener:
        class: 'BasicFlowBundle\EventListener\FlowListener'
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
